---
# tasks file for mybalancer
- name: Install Haproxy balancer
  package:
    name: 
      - haproxy
    state: present

# Install HTTPD package
- name: Install Apache HTTP server (apache2)
  package:
    name: apache2
    state: present

# Configuration template of Haproxy will be replaced by haproxy.j2 configuration
- name: Configuration Template of Haproxy
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restarted load balancer

# Haproxy service will be started and enabled 
- name: Start and Enable Haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes

# Template for Apache index.html
- name: Create Apache index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

# Restart Apache service
- name: Restart Apache and firewalld services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - apache2
    
#---------------------------------------------------------------------
# Optional: Enable HTTP service in firewall (if using another firewall management service)


# - name: Enable HTTP service in firewall
#   command: firewall-cmd --zone=public --add-service=http --permanent
#   become: true
#   when: ansible_distribution == "CentOS"

# Reload firewalld
#- name: Reload firewalld to apply changes
#  systemd:
#    name: firewalld
#    state: reloaded
#  become: true
